# Generated by Django 3.0.6 on 2021-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=15)),
                ('card_no', models.IntegerField()),
            ],
        ),
    ]
