# Generated by Django 3.0.6 on 2021-02-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_january'),
    ]

    operations = [
        migrations.AddField(
            model_name='january',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
