# Generated by Django 3.0.6 on 2021-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210203_0251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='January',
            new_name='Month',
        ),
    ]
