# Generated by Django 3.0.6 on 2021-02-03 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210203_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=5), size=31),
        ),
    ]
