# Generated by Django 3.0.6 on 2021-02-03 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210203_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=31),
        ),
    ]
