# Generated by Django 3.0.6 on 2021-02-03 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210203_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), default=['99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999', '99999'], size=31),
        ),
    ]
