# Generated by Django 3.0.6 on 2021-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_no',
            field=models.CharField(max_length=50),
        ),
    ]
