# Generated by Django 3.0.6 on 2021-02-02 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210202_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=31)),
            ],
        ),
    ]
