# Generated by Django 3.0.6 on 2021-02-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_january_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='january',
            name='month',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='january',
            name='roll_number',
            field=models.ForeignKey(default='19D070061', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='january',
            unique_together={('data', 'month')},
        ),
        migrations.RemoveField(
            model_name='january',
            name='name',
        ),
    ]
