# Generated by Django 3.0.6 on 2021-02-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210203_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
