# Generated by Django 3.0.6 on 2021-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210203_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
